#!/bin/bash
echo "=== REPAZOO DEPLOYMENT VERIFICATION ==="
echo ""
echo "1. Docker Containers:"
docker ps --format "  {{.Names}}: {{.Status}}" | grep -E "(repazoo|ollama)" || echo "  No containers found"
echo ""
echo "2. Database Table:"
docker exec -i repazoo-postgres psql -U postgres -d postgres -c "\d public.reputation_reports" 2>&1 | head -10 || echo "  Table check failed"
echo ""
echo "3. Files Created:"
ls -lh /root/repazoo/n8n/workflows/opus-orchestration-fixed.json 2>/dev/null && echo "  ✅ Workflow file exists" || echo "  ❌ Workflow file missing"
ls -lh /root/repazoo/frontend/src/features/dashboard/components/recent-scans.tsx 2>/dev/null && echo "  ✅ Frontend component exists" || echo "  ❌ Component missing"
ls -lh /root/repazoo/DEPLOYMENT_COMPLETE.md 2>/dev/null && echo "  ✅ Deployment docs exist" || echo "  ❌ Docs missing"
echo ""
echo "4. Quick Service Check:"
curl -sf http://localhost:5678/healthz > /dev/null 2>&1 && echo "  ✅ n8n: OK" || echo "  ❌ n8n: FAIL"
curl -sf http://ai.repazoo.com/api/tags > /dev/null 2>&1 && echo "  ✅ Ollama: OK" || echo "  ❌ Ollama: FAIL"
echo ""
echo "=== VERIFICATION COMPLETE ==="
